apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: podinfonew
spec:
  hosts:
  - "podinfonew.aks.mrlotfy.xyz"
  gateways:
  - podinfonew-gateway-ext
  http:
    - route:
      - destination:
          port:
            number: 9898
          host: podinfonew
