apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: podinfo2
spec:
  hosts:
  - "podinfo2.aks.mrlotfy.xyz"
  gateways:
  - podinfo2-gateway-ext
  http:
    - route:
      - destination:
          port:
            number: 9898
          host: podinfo2
